networks:
  traefik:
    # The external option allows this network to be used by
    # Traefik containers declared in other stack files
    external: true

services:
  whoami:
    image: traefik/whoami:${WHOAMI_IMAGE_VERSION:-latest}
    # We add the traefik network to the container so Traefik and this container
    # are on the same network
    networks:
      - traefik
    # We expose the port 80 to the Traefik container instead of the host
    expose:
      - 80
    # We add the labels to the container to allow it to be discovered by Traefik
    labels:
      ## Traefik
      - traefik.enable=true
      - traefik.docker.network=traefik
      ## HTTP
      - traefik.http.routers.whoami.entrypoints=http
      # We use a Path Prefix rule to match the /whoami path
      - traefik.http.routers.whoami.rule=PathPrefix(`/whoami`)
