networks:
  traefik:
    external: true

services:
  whoami:
    image: traefik/whoami:${WHOAMI_IMAGE_VERSION:-latest}
    networks:
      - traefik
    expose:
      - 80
    labels:
      ## Traefik
      - traefik.enable=true
      - traefik.docker.network=traefik
      ## HTTP
      - traefik.http.routers.whoami.entrypoints=http
      # We use Host and PathPrefix rules at the same time
      - traefik.http.routers.whoami.rule=Host(`${WHOAMI_FULLY_QUALIFIED_DOMAIN_NAME}`) && PathPrefix(`/whoami`)
