networks:
  traefik_network:
    # We use an external network as it is created by Traefik
    external: true

services:
  whoami:
    image: traefik/whoami:${WHOAMI_IMAGE_VERSION:-latest}
    networks:
      - traefik_network
    # By using the `expose` key, we expose the port 80 of the container to the
    # other containers in the same network without exposing it to the host
    # machine
    expose:
      - 80
    labels:
      ## Traefik
      - traefik.enable=true
      - traefik.docker.network=traefik_network
      ## HTTPS
      - traefik.http.routers.whoami.entrypoints=https
      - traefik.http.routers.whoami.rule=Host(`${WHOAMI_FULLY_QUALIFIED_DOMAIN_NAME}`)
