services:
  openssh-server:
    # Use the version set in the `.env` file, or default to the latest version
    image: lscr.io/linuxserver/openssh-server:${OPENSSH_SERVER_IMAGE_VERSION:-latest}
    # If the container stops, restart it automatically
    restart: unless-stopped
    env_file:
      # Set the environment variables from the `openssh-server.env` file
      - openssh-server.env
    ports:
      # Instead of using the default 22 port, we use 2222 to avoid conflicts
      - 2222:2222
    volumes:
      # Mount the config directory from the host
      - ./config:/config
